### ISSUE TITLE
It fails silently.

### ISSUE THREAD

**Issue by jooddang** [terra-project/terra-py#37]
I tried to send token on mainnet for an account that doesn't have any token. The call finished silently without any message and I can't see any transaction on finder.
It should have not sent any token because it doesn't have any, still I can't see what has happened and what went wrong.

**Comment by etienne-napoleone** [comment]
Should be fixed in v0.5.0 https://github.com/terra-project/terra-py/releases/tag/v0.5.0 (release #38).
Can you confirm?

**Comment by jooddang** [comment]
I don't think it's fixed.
I just tried to send tokens on vodka-0001 with `msg.bank.MsgSend`, and it returned nothing, and no transaction has made.

**Comment by dokwon** [comment]
Vodka 0001 is a retired testnet, not sure how you were able to connect to
it. Can you try against the latest?

**Comment by jooddang** [comment]
is it retired? then, what's the latest one? I was told to use `vodka` testnet from your team.
also, I see vodka-0001 from finder.
![image](https://user-images.githubusercontent.com/1115552/71387310-15e0aa00-25a8-11ea-89fa-f373977a1221.png)

**Comment by dokwon** [comment]
Apologies. Can you try against soju 00013 or mainnet columbus-3?

**Comment by etienne-napoleone** [comment]
To use soju-0013 you'd need to do it the following way:
```python
import terra

acc = terra.Account(mnemonic="...", chain_id="soju-0013")
terra.api.client.Client.URL = "https://soju-lcd.terra.dev"
```

I think this part should be refactored to be more user friendly. see #40

**Comment by jooddang** [comment]
oh, I think it fails with messages after version upgrade to 0.6.0. Feel free to close this issue. And, I heard from Yun that `vodka-0001` is not retired.

**Comment by etienne-napoleone** [comment]
I could not reproduce a situation where it fails silently.
As the `terra.api` methods are just an http wrapper around lcd endpoints, from my experience it either raise an exception is status != 200 or another kind of error occured or return the http response.
